#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
#
#  h2:
#    console:
#      enabled: true
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
  spring:
    jpa:
     database: POSTGRESQL
     show-sql: true
     hibernate:
       ddl-auto: create-drop
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver

